#!/usr/bin/env node
// Turns assets/hearts/*.svg into src/hearts.js, which the overlay and the settings preview
// both read. They need the markup inside the document, not as an <img>, because the colour
// picker and the heart rate zones recolour it through currentColor.
//
//   npm run hearts
const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, '..', 'assets', 'hearts');
const OUT = path.join(__dirname, '..', 'src', 'hearts.js');

// Nicer than deriving every label from a file name
const LABELS = {
  angular: 'Angular', bandaged: 'Bandaged', bite: 'Bite', crossbones: 'Crossbones',
  filled: 'Filled', glossy: 'Glossy', 'in-love': 'In love', melting: 'Melting',
  mosaic: 'Mosaic', 'on-fire': 'On fire', outline: 'Outline', pixel: 'Pixel',
  'pixel-outline': 'Pixel outline', rays: 'Rays', rings: 'Rings', slim: 'Slim',
  sparkle: 'Sparkle', trio: 'Trio', wide: 'Wide', wings: 'Wings',
};

const sentence = (id) => id.replace(/-/g, ' ').replace(/^./, (c) => c.toUpperCase());

function normalise(svg, name) {
  let s = svg
    .replace(/<\?xml[^>]*\?>/g, '')
    .replace(/<!DOCTYPE[^>]*>/gi, '')
    .replace(/<!--[\s\S]*?-->/g, '')
    .trim();

  if (!/viewBox="/.test(s)) throw new Error(`${name}: no viewBox, the shape cannot be scaled`);

  // The size comes from the settings slider, not from the file
  s = s.replace(/<svg([^>]*)>/, (m, attrs) =>
    '<svg' + attrs.replace(/\s(width|height)="[^"]*"/g, '') +
    ' style="width:1em;height:1em;fill:currentColor;display:block;">');

  // Everything follows the chosen colour. fill="none" is a real instruction and stays.
  s = s.replace(/fill="(?!none)[^"]*"/g, 'fill="currentColor"')
       .replace(/fill:\s*(?!none)[^;"}]+/g, 'fill:currentColor');

  for (const [pattern, what] of [[/<style/i, '<style> block'], [/Gradient/, 'gradient'],
                                 [/<filter|filter="/i, 'filter'], [/<text/i, '<text>'],
                                 [/base64/i, 'embedded bitmap']]) {
    if (pattern.test(s)) console.warn(`  warning  ${name}: contains a ${what}, the colour setting will not reach it`);
  }
  return s.replace(/\s+/g, ' ').replace(/> </g, '><');
}

const files = fs.readdirSync(SRC).filter((f) => f.endsWith('.svg')).sort();
if (!files.length) { console.error(`No .svg files in ${SRC}`); process.exit(1); }

const shapes = files.map((f) => {
  const id = path.basename(f, '.svg');
  return [id, { label: LABELS[id] || sentence(id), svg: normalise(fs.readFileSync(path.join(SRC, f), 'utf8'), f) }];
});

const body = shapes.map(([id, s]) =>
  `  ${JSON.stringify(id)}: { label: ${JSON.stringify(s.label)}, svg: ${JSON.stringify(s.svg)} },`).join('\n');

fs.writeFileSync(OUT, `// Generated by tools/build-hearts.js from assets/hearts/*.svg — do not edit by hand.
// Add a shape by dropping an .svg in that folder and running: npm run hearts
window.HEART_SHAPES = {
${body}
};
`);

const kb = (fs.statSync(OUT).size / 1024).toFixed(1);
console.log(`${shapes.length} shapes -> src/hearts.js (${kb} kB)`);
console.log(shapes.map(([id]) => id).join(', '));
